[package]
name = "rust_lib_resonance_network_wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
# NOTE: Quantus chain dependencies.
qp-poseidon = { version = "1.0.1", default-features = false }
qp-rusty-crystals-dilithium = { git = "https://github.com/Quantus-Network/qp-rusty-crystals.git", branch = "master" }
qp-rusty-crystals-hdwallet = { git = "https://github.com/Quantus-Network/qp-rusty-crystals.git", branch = "master" }

bip39 = "2.1.0"
flutter_rust_bridge = "=2.9.0"
hex = "0.4.3"
nam-tiny-hderive = "0.3.1-nam.0"
sp-core = "35.0.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
