name: quantus_workspace
packages:
  - mobile-app
  - miner-app
  - quantus_sdk

ide:
  intellij:
    enabled: false

# Shared dependency versions across all packages
dependency_overrides:
  # Workspace packages - local paths
  quantus_sdk:
    path: ./quantus_sdk

  # Polkadart ecosystem - latest versions
  polkadart: ^0.7.1
  polkadart_keyring: ^0.7.0
  polkadart_cli: ^0.7.1

  # Crypto and encoding - latest versions
  bip39_mnemonic: ^3.0.9
  crypto: ^3.0.6
  ss58: ^1.3.1
  convert: ^3.0.0

  # HTTP and networking
  http: ^1.4.0

  # Storage and preferences
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4

  # Math and utilities
  decimal: ^3.2.2
  quiver: ^3.1.0
  hex: ^0.2.0
  intl: ^0.20.2
  path: ^1.9.1

  # UI and Graphics (Flutter specific)
  flutter_svg: ^2.2.0
  qr_flutter: ^4.1.0
  flash: ^3.1.1
  cupertino_icons: ^1.0.6

  # Mobile/Flutter specific
  video_player: ^2.10.0
  mobile_scanner: ^7.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.1.2
  permission_handler: ^12.0.1

  # State management and architecture
  provider: ^6.1.2
  hooks_riverpod: ^2.5.0
  flutter_hooks: ^0.21.2
  go_router: ^15.2.0

  # Notifications and UI feedback
  another_flushbar: ^1.10.2

  # Development and tooling
  logger: ^2.5.0
  path_provider: ^2.0.0

  # Rust bridge
  flutter_rust_bridge: ^2.10.0

  # Dev dependencies - latest versions
  flutter_lints: ^6.0.0
  test: ^1.25.0

scripts:
  # Analyze all packages
  analyze:
    description: Analyze all packages in the workspace
    run: melos exec -- dart analyze .

  # Format all packages
  format:
    description: Format all packages in the workspace
    run: melos exec -- dart format .

  # Test all packages
  test:
    description: Run tests in all packages
    run: melos exec --fail-fast -- dart test

  # Get dependencies for all packages
  get:
    description: Get dependencies for all packages
    run: melos exec -- flutter pub get

  # Clean all packages
  clean:
    description: Clean all packages
    run: melos exec -- flutter clean

  # Generate pubspec_overrides.yaml files
  bootstrap:
    description: Bootstrap workspace with dependency overrides
    run: melos bootstrap

  # Generate polkadart bindings for quantus_sdk
  generate:
    description: Generate polkadart bindings
    run: cd quantus_sdk && dart run polkadart_cli:generate -v

  # Full setup - bootstrap, get deps, generate, and analyze
  setup:
    description: Full workspace setup
    run: |
      melos bootstrap
      melos get
      melos generate
      melos analyze

  # Update all packages to latest versions
  upgrade:
    description: Upgrade all packages to latest versions
    run: melos exec -- dart pub upgrade --major-versions

  # Validate all pubspec.yaml files are in sync
  validate:
    description: Validate all pubspec files are properly configured
    run: melos list --json
