name: resonance_network_wallet
description: A Flutter wallet for the Resonance Network blockchain.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  qr_flutter: ^4.0.0
  polkadot_dart: ^3.3.0  # Replace with actual version when available

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/ 