name: resonance_network_wallet
description: A Flutter wallet for the Resonance Network blockchain.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.3
  hex: ^0.2.0
  polkadart: ^0.6.1
  polkadart_keyring: ^0.6.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  ss58: ^1.3.1
  bip39_mnemonic: ^3.0.9
  # bip39: ^1.0.6
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  rust_lib_resonance_network_wallet:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  human_checksum:
    git:
      url: https://github.com/Resonance-Network/human-checkphrase.git
      path: dart

# Generate Polkadart bindings
# dart pub run polkadart_cli:generate -v
  quiver: any
  convert: any
  polkadart_cli: ^0.6.1

polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
      polkadot: wss://rpc.polkadot.io
      resonance: ws://127.0.0.1:9944

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/BG_00 1.png
    - assets/text/crypto_checksum_bip39.txt
    - assets/send_icon.png
    - assets/send_icon.svg
    - assets/receive_icon.png
    - assets/receive_icon.svg
    - assets/swap_icon.svg
    - assets/scan.svg
    - assets/main_wallet_title_logo.svg
    - assets/account_list_icon.svg
    - assets/RES icon.svg

  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700 