name: resonance_network_wallet
description: A Flutter wallet for the Resonance Network blockchain.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  polkadart: ^0.6.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  ss58: ^1.3.1
  bip39: ^1.0.6
  intl: ^0.20.2
  rust_lib_resonance_network_wallet:
    path: rust_builder
  flutter_rust_bridge: 2.9.0

# Generate Polkadart bindings
# dart pub run polkadart_cli:generate -v
  quiver: any
  convert: any
  polkadart_cli: ^0.6.1

polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
      polkadot: wss://rpc.polkadot.io
      resonance: ws://127.0.0.1:9944

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/ 