name: quantus_sdk
description: Shared Quantus Dart + Rust bindings and services
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_rust_bridge: 2.9.0
  rust_lib_resonance_network_wallet:
    path: ./rust_builder
  polkadart: ^0.6.1
  polkadart_keyring: ^0.6.1
  human_checksum:
    git:
      url: https://github.com/Resonance-Network/human-checkphrase.git
      path: dart
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  decimal: ^2.3.3
  flash: ^3.1.1
  http: ^1.4.0

  quiver: ^3.1.0
  flutter:
    sdk: flutter
  bip39_mnemonic: ^3.0.9
  crypto: ^3.0.6
  ss58: ^1.3.1
  convert: ^3.0.0
  polkadart_cli: ^0.6.1

# Generate Polkadart bindings
# dart pub run polkadart_cli:generate -v

polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
      polkadot: wss://rpc.polkadot.io
      resonance: ws://localhost:9944 # Local dev node 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
