name: quantus_sdk
description: Shared Quantus Dart + Rust bindings and services
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Rust bridge and local dependencies
  flutter_rust_bridge: 2.9.0 # Version managed by melos.yaml
  rust_lib_resonance_network_wallet:
    path: ./rust_builder
  
  # Polkadart ecosystem (managed by melos.yaml)
  polkadart: # Version managed by melos.yaml
  polkadart_keyring: # Version managed by melos.yaml
  polkadart_cli: # Version managed by melos.yaml
  
  # Crypto and encoding
  bip39_mnemonic: # Version managed by melos.yaml
  crypto: # Version managed by melos.yaml
  ss58: # Version managed by melos.yaml
  convert: # Version managed by melos.yaml
  
  # Storage, networking, and utilities
  shared_preferences: # Version managed by melos.yaml
  flutter_secure_storage: # Version managed by melos.yaml
  http: # Version managed by melos.yaml
  decimal: # Version managed by melos.yaml
  quiver: # Version managed by melos.yaml
  intl: # Version managed by melos.yaml
  
  # UI feedback
  flash: # Version managed by melos.yaml
  
  # Git dependencies (can't be managed by melos dependency_overrides)
  human_checksum:
    git:
      url: https://github.com/Quantus-Network/human-checkphrase.git
      path: dart

# Generate Polkadart bindings
# dart pub run polkadart_cli:generate -v

polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
      polkadot: wss://rpc.polkadot.io
      resonance: ws://localhost:9944 # Local dev node 

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: # Version managed by melos.yaml
  flutter_lints: # Version managed by melos.yaml
  integration_test:
    sdk: flutter
