name: quantus_sdk
description: Shared Quantus Dart + Rust bindings and services
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_rust_bridge: ^2.9.0 # Match the version in mobile-app
  rust_lib_resonance_network_wallet:
    path: ./rust_builder
  polkadart: ^0.6.1
  polkadart_keyring: ^0.6.1
  human_checksum:
    git:
      url: https://github.com/Resonance-Network/human-checkphrase.git
      path: dart
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  decimal: ^2.3.3
  flash: ^3.1.1
  http: ^1.4.0

  quiver: any
  flutter:
    sdk: flutter
  bip39_mnemonic: any
  crypto: any
  ss58: any
  convert: any
polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
      polkadot: wss://rpc.polkadot.io
      resonance: wss://a.t.res.fm:443 # This is only used for the code generator, can be local net 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
