// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_ml_dsa`, `to_ml_dsa`

void setDefaultSs58Prefix({required int prefix}) =>
    RustLib.instance.api.crateApiCryptoSetDefaultSs58Prefix(prefix: prefix);

/// Convert public key to accountId32 in ss58check format
String toAccountId({required Keypair obj}) =>
    RustLib.instance.api.crateApiCryptoToAccountId(obj: obj);

/// Convert key in ss58check format to accountId32
Uint8List ss58ToAccountId({required String s}) =>
    RustLib.instance.api.crateApiCryptoSs58ToAccountId(s: s);

Keypair generateKeypair({required String mnemonicStr}) => RustLib.instance.api
    .crateApiCryptoGenerateKeypair(mnemonicStr: mnemonicStr);

Keypair generateDerivedKeypair({
  required String mnemonicStr,
  required String path,
}) => RustLib.instance.api.crateApiCryptoGenerateDerivedKeypair(
  mnemonicStr: mnemonicStr,
  path: path,
);

Keypair generateKeypairFromSeed({required List<int> seed}) =>
    RustLib.instance.api.crateApiCryptoGenerateKeypairFromSeed(seed: seed);

Uint8List signMessage({
  required Keypair keypair,
  required List<int> message,
  U8Array32? entropy,
}) => RustLib.instance.api.crateApiCryptoSignMessage(
  keypair: keypair,
  message: message,
  entropy: entropy,
);

Uint8List signMessageWithPubkey({
  required Keypair keypair,
  required List<int> message,
  U8Array32? entropy,
}) => RustLib.instance.api.crateApiCryptoSignMessageWithPubkey(
  keypair: keypair,
  message: message,
  entropy: entropy,
);

bool verifyMessage({
  required Keypair keypair,
  required List<int> message,
  required List<int> signature,
}) => RustLib.instance.api.crateApiCryptoVerifyMessage(
  keypair: keypair,
  message: message,
  signature: signature,
);

Keypair crystalAlice() => RustLib.instance.api.crateApiCryptoCrystalAlice();

Keypair crystalBob() => RustLib.instance.api.crateApiCryptoCrystalBob();

Keypair crystalCharlie() => RustLib.instance.api.crateApiCryptoCrystalCharlie();

Uint8List deriveHdPath({required List<int> seed, required String path}) =>
    RustLib.instance.api.crateApiCryptoDeriveHdPath(seed: seed, path: path);

BigInt publicKeyBytes() => RustLib.instance.api.crateApiCryptoPublicKeyBytes();

BigInt secretKeyBytes() => RustLib.instance.api.crateApiCryptoSecretKeyBytes();

BigInt signatureBytes() => RustLib.instance.api.crateApiCryptoSignatureBytes();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HDLatticeError>>
abstract class HdLatticeError implements RustOpaqueInterface {}

class Keypair {
  final Uint8List publicKey;
  final Uint8List secretKey;

  const Keypair({required this.publicKey, required this.secretKey});

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Keypair &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
