// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'crypto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes`, `check_account_id`, `decode_wire`, `require_ml_dsa_65`, `text`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WireAccessKeyPermission`, `WireAccessKey`, `WireAction`, `WireFunctionCallPermission`, `WirePublicKey`, `WireTransaction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deserialize_reader`, `deserialize_reader`, `deserialize_reader`, `deserialize_reader`, `deserialize_reader`, `deserialize_reader`, `deserialize_variant`, `deserialize_variant`, `deserialize_variant`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `serialize`, `serialize`, `serialize`, `serialize`, `serialize`, `serialize`

/// Decode a borsh `TransactionV0`. Refuses trailing bytes.
NearTransaction decodeNearTransaction({required List<int> transaction}) =>
    RustLib.instance.api.crateApiNearDecodeNearTransaction(transaction: transaction);

/// SHA-256 of the transaction bytes: the message NEAR signs and verifies.
Uint8List nearTransactionHash({required List<int> transaction}) =>
    RustLib.instance.api.crateApiNearNearTransactionHash(transaction: transaction);

/// Sign a borsh `TransactionV0` for NEAR. Refuses unless `keypair` is
/// ML-DSA-65 *and* is the key the transaction declares. Returns
/// `signature ‖ public_key` (3309 + 1952 bytes).
Uint8List signNearTransaction({required Keypair keypair, required List<int> transaction, U8Array32? entropy}) =>
    RustLib.instance.api.crateApiNearSignNearTransaction(keypair: keypair, transaction: transaction, entropy: entropy);

/// Whether `signature` is a valid pure ML-DSA-65 signature by `public_key`
/// over the transaction, as the NEAR runtime checks it.
bool verifyNearSignature({
  required List<int> publicKey,
  required List<int> transaction,
  required List<int> signature,
}) => RustLib.instance.api.crateApiNearVerifyNearSignature(
  publicKey: publicKey,
  transaction: transaction,
  signature: signature,
);

/// The account's key in NEAR text form, `ml-dsa-65:<base58>`. This is the
/// `--signer-public-key` near-cli-rs takes and what an `AddKey` carries.
String nearPublicKeyText({required Keypair keypair}) =>
    RustLib.instance.api.crateApiNearNearPublicKeyText(keypair: keypair);

/// The on-chain handle of the key, `ml-dsa-65-hash:<base58>`: what
/// `view_access_key_list` shows, SHA3-256 of a domain tag and the key.
String nearPublicKeyHandle({required Keypair keypair}) =>
    RustLib.instance.api.crateApiNearNearPublicKeyHandle(keypair: keypair);

/// One action of a NEAR transaction, flattened for display. Which fields are
/// set depends on [`NearAction::kind`]; amounts are yoctoNEAR (24 decimals)
/// and keys are NEAR text form (`<scheme>:<base58>`).
///
/// A flat struct rather than an enum with payloads: that keeps the Dart side
/// a plain class instead of a generated sealed hierarchy.
class NearAction {
  final NearActionKind kind;

  /// `FunctionCall`: the method; `DeleteAccount`: the beneficiary;
  /// `AddKey` (function-call key): the contract the key may call.
  final String? target;

  /// `FunctionCall`: raw call arguments (usually JSON).
  final Uint8List? args;

  /// `FunctionCall`: prepaid gas.
  final BigInt? gas;

  /// `Transfer`/`FunctionCall`: attached deposit; `Stake`: staked amount;
  /// `AddKey` (function-call key): gas allowance, `None` = unlimited.
  final BigInt? amount;

  /// `Stake`/`AddKey`/`DeleteKey`: the key concerned.
  final String? publicKey;

  /// `AddKey`: whether the key gets full access.
  final bool fullAccess;

  /// `AddKey` (function-call key): the methods it may call; empty = any.
  final List<String> methodNames;

  /// `DeployContract`: size of the code blob.
  final int? codeLen;

  /// `DeployContract`: SHA-256 of the code, how NEAR identifies contract
  /// code, so a signer can compare it with the artifact they meant to deploy.
  final Uint8List? codeHash;

  const NearAction({
    required this.kind,
    this.target,
    this.args,
    this.gas,
    this.amount,
    this.publicKey,
    required this.fullAccess,
    required this.methodNames,
    this.codeLen,
    this.codeHash,
  });

  static Future<NearAction> default_() => RustLib.instance.api.crateApiNearNearActionDefault();

  @override
  int get hashCode =>
      kind.hashCode ^
      target.hashCode ^
      args.hashCode ^
      gas.hashCode ^
      amount.hashCode ^
      publicKey.hashCode ^
      fullAccess.hashCode ^
      methodNames.hashCode ^
      codeLen.hashCode ^
      codeHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearAction &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          target == other.target &&
          args == other.args &&
          gas == other.gas &&
          amount == other.amount &&
          publicKey == other.publicKey &&
          fullAccess == other.fullAccess &&
          methodNames == other.methodNames &&
          codeLen == other.codeLen &&
          codeHash == other.codeHash;
}

/// The kind of a [`NearAction`]. Everything but `Transfer` and
/// `FunctionCall` changes who controls the account or what code it runs.
enum NearActionKind {
  createAccount,
  deployContract,
  functionCall,
  transfer,
  stake,
  addKey,
  deleteKey,
  deleteAccount;

  static Future<NearActionKind> default_() => RustLib.instance.api.crateApiNearNearActionKindDefault();
}

/// A decoded NEAR transaction, ready to display.
class NearTransaction {
  final String signerId;

  /// The key that must sign, in NEAR text form.
  final String publicKey;

  /// Raw bytes of that key; compare against a [`Keypair::public_key`].
  final Uint8List publicKeyBytes;

  /// Whether the signing key is ML-DSA-65 — the only scheme a Quantus
  /// account can sign for.
  final bool signsWithMlDsa65;
  final BigInt nonce;
  final String receiverId;

  /// Base58, as NEAR tooling prints it.
  final String blockHash;

  /// SHA-256 of the transaction bytes: what gets signed, and the id the
  /// NEAR RPC reports (as base58) once submitted.
  final Uint8List hash;
  final List<NearAction> actions;

  const NearTransaction({
    required this.signerId,
    required this.publicKey,
    required this.publicKeyBytes,
    required this.signsWithMlDsa65,
    required this.nonce,
    required this.receiverId,
    required this.blockHash,
    required this.hash,
    required this.actions,
  });

  @override
  int get hashCode =>
      signerId.hashCode ^
      publicKey.hashCode ^
      publicKeyBytes.hashCode ^
      signsWithMlDsa65.hashCode ^
      nonce.hashCode ^
      receiverId.hashCode ^
      blockHash.hashCode ^
      hash.hashCode ^
      actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearTransaction &&
          runtimeType == other.runtimeType &&
          signerId == other.signerId &&
          publicKey == other.publicKey &&
          publicKeyBytes == other.publicKeyBytes &&
          signsWithMlDsa65 == other.signsWithMlDsa65 &&
          nonce == other.nonce &&
          receiverId == other.receiverId &&
          blockHash == other.blockHash &&
          hash == other.hash &&
          actions == other.actions;
}
