// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_block_hash_internal`, `compute_merkle_positions`, `parse_hex_32`, `parse_hex`, `short_hex_bytes`, `short_hex`, `ss58_to_bytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Derive a wormhole address pair from a mnemonic.
///
/// # Arguments
/// * `mnemonic` - The 24-word BIP39 mnemonic phrase
/// * `purpose` - The purpose index (0 = mobile sends, 1 = miner rewards)
/// * `index` - The address index within the purpose
///
/// # Returns
/// A `WormholePairResult` containing the address, first_hash, and secret.
///
/// # Example
/// ```ignore
/// let result = derive_wormhole_pair(
///     "word1 word2 ... word24".to_string(),
///     1,  // purpose: miner rewards
///     0,  // index: first address
/// )?;
/// println!("Rewards inner hash (for --rewards-inner-hash): {}", result.first_hash_ss58);
/// println!("Wormhole address (on-chain account): {}", result.address);
/// ```
WormholePairResult deriveWormholePair({
  required String mnemonic,
  required int purpose,
  required int index,
}) => RustLib.instance.api.crateApiWormholeDeriveWormholePair(
  mnemonic: mnemonic,
  purpose: purpose,
  index: index,
);

/// Convert a first_hash (rewards preimage) to its corresponding wormhole address.
///
/// This computes the address exactly as the chain and ZK circuit do:
/// - Convert first_hash (32 bytes) to 4 field elements using unsafe_digest_bytes_to_felts
///   (8 bytes per element)
/// - Hash once without padding using hash_variable_length
///
/// The wormhole address derivation is:
/// - secret -> hash(salt + secret) = first_hash (preimage for node)
/// - first_hash -> hash(first_hash) = address
///
/// # Arguments
/// * `first_hash_hex` - The first_hash bytes as hex string (with or without 0x prefix)
///
/// # Returns
/// The wormhole address as SS58 string.
String firstHashToAddress({required String firstHashHex}) => RustLib
    .instance
    .api
    .crateApiWormholeFirstHashToAddress(firstHashHex: firstHashHex);

/// Get the wormhole HD derivation path for a given purpose and index.
///
/// # Arguments
/// * `purpose` - The purpose index (0 = mobile sends, 1 = miner rewards)
/// * `index` - The address index within the purpose
///
/// # Returns
/// The full HD derivation path string.
String getWormholeDerivationPath({required int purpose, required int index}) =>
    RustLib.instance.api.crateApiWormholeGetWormholeDerivationPath(
      purpose: purpose,
      index: index,
    );

/// Compute the nullifier for a wormhole UTXO.
///
/// The nullifier is a deterministic hash of (secret, transfer_count) that prevents
/// double-spending. Once revealed on-chain, the UTXO cannot be spent again.
///
/// # Arguments
/// * `secret_hex` - The wormhole secret (32 bytes, hex with 0x prefix)
/// * `transfer_count` - The transfer count from NativeTransferred event
///
/// # Returns
/// The nullifier as hex string with 0x prefix.
String computeNullifier({
  required String secretHex,
  required BigInt transferCount,
}) => RustLib.instance.api.crateApiWormholeComputeNullifier(
  secretHex: secretHex,
  transferCount: transferCount,
);

/// Derive the wormhole address from a secret.
///
/// This computes the unspendable account address that corresponds to the given secret.
///
/// # Arguments
/// * `secret_hex` - The wormhole secret (32 bytes, hex with 0x prefix)
///
/// # Returns
/// The wormhole address as SS58 string.
String deriveAddressFromSecret({required String secretHex}) => RustLib
    .instance
    .api
    .crateApiWormholeDeriveAddressFromSecret(secretHex: secretHex);

/// Quantize an amount from planck (12 decimals) to the circuit format (2 decimals).
///
/// The circuit uses quantized amounts for privacy. This function converts
/// a full-precision amount to the quantized format.
///
/// # Arguments
/// * `amount_planck` - Amount in planck (smallest unit, 12 decimal places)
///
/// # Returns
/// Quantized amount (2 decimal places) that can be used in proof outputs.
int quantizeAmount({required BigInt amountPlanck}) => RustLib.instance.api
    .crateApiWormholeQuantizeAmount(amountPlanck: amountPlanck);

/// Dequantize an amount from circuit format (2 decimals) back to planck (12 decimals).
///
/// # Arguments
/// * `quantized_amount` - Amount in circuit format (2 decimal places)
///
/// # Returns
/// Amount in planck (12 decimal places).
BigInt dequantizeAmount({required int quantizedAmount}) => RustLib.instance.api
    .crateApiWormholeDequantizeAmount(quantizedAmount: quantizedAmount);

/// Compute the output amount after fee deduction.
///
/// The circuit enforces that output amounts don't exceed input minus fee.
/// Use this function to compute the correct output amount for proof generation.
///
/// Formula: `output = input * (10000 - fee_bps) / 10000`
///
/// # Arguments
/// * `input_amount` - Input amount in quantized units (from quantize_amount)
/// * `fee_bps` - Fee rate in basis points (e.g., 10 = 0.1%)
///
/// # Returns
/// Maximum output amount in quantized units.
///
/// # Example
/// ```ignore
/// let input = quantize_amount(383561629241)?; // 38 in quantized
/// let output = compute_output_amount(input, 10); // 37 (after 0.1% fee)
/// ```
int computeOutputAmount({required int inputAmount, required int feeBps}) =>
    RustLib.instance.api.crateApiWormholeComputeOutputAmount(
      inputAmount: inputAmount,
      feeBps: feeBps,
    );

/// Get the batch size for proof aggregation.
///
/// # Arguments
/// * `bins_dir` - Path to circuit binaries directory
///
/// # Returns
/// Number of proofs that must be aggregated together.
BigInt getAggregationBatchSize({required String binsDir}) => RustLib
    .instance
    .api
    .crateApiWormholeGetAggregationBatchSize(binsDir: binsDir);

/// Encode digest logs from RPC format to SCALE-encoded bytes.
///
/// The RPC returns digest logs as an array of hex-encoded SCALE bytes.
/// This function properly encodes them as a SCALE Vec<DigestItem> which
/// matches what the circuit expects.
///
/// # Arguments
/// * `logs_hex` - Array of hex-encoded digest log items from RPC
///
/// # Returns
/// SCALE-encoded digest as hex string (with 0x prefix), padded/truncated to 110 bytes.
///
/// # Example
/// ```ignore
/// // From RPC: header.digest.logs = ["0x0642...", "0x0561..."]
/// let digest_hex = encode_digest_from_rpc_logs(vec!["0x0642...".into(), "0x0561...".into()])?;
/// ```
String encodeDigestFromRpcLogs({required List<String> logsHex}) => RustLib
    .instance
    .api
    .crateApiWormholeEncodeDigestFromRpcLogs(logsHex: logsHex);

/// Create a new proof generator.
///
/// This loads ~171MB of circuit data, so it's expensive. Call once and reuse.
///
/// # Arguments
/// * `bins_dir` - Path to directory containing prover.bin and common.bin
Future<WormholeProofGenerator> createProofGenerator({
  required String binsDir,
}) =>
    RustLib.instance.api.crateApiWormholeCreateProofGenerator(binsDir: binsDir);

/// Create a new proof aggregator.
///
/// # Arguments
/// * `bins_dir` - Path to directory containing aggregator circuit files
Future<WormholeProofAggregator> createProofAggregator({
  required String binsDir,
}) => RustLib.instance.api.crateApiWormholeCreateProofAggregator(
  binsDir: binsDir,
);

/// Compute block hash from header components.
///
/// This matches the Poseidon block hash computation used by the Quantus chain.
/// The hash is computed over the SCALE-encoded header components.
///
/// # Arguments
/// * `parent_hash_hex` - Parent block hash (32 bytes, hex with 0x prefix)
/// * `state_root_hex` - State root (32 bytes, hex with 0x prefix)
/// * `extrinsics_root_hex` - Extrinsics root (32 bytes, hex with 0x prefix)
/// * `zk_tree_root_hex` - ZK tree root (32 bytes, hex with 0x prefix)
/// * `block_number` - Block number
/// * `digest_hex` - SCALE-encoded digest (hex with 0x prefix, from encode_digest_from_rpc_logs)
///
/// # Returns
/// Block hash as hex string with 0x prefix.
String computeBlockHash({
  required String parentHashHex,
  required String stateRootHex,
  required String extrinsicsRootHex,
  required String zkTreeRootHex,
  required int blockNumber,
  required String digestHex,
}) => RustLib.instance.api.crateApiWormholeComputeBlockHash(
  parentHashHex: parentHashHex,
  stateRootHex: stateRootHex,
  extrinsicsRootHex: extrinsicsRootHex,
  zkTreeRootHex: zkTreeRootHex,
  blockNumber: blockNumber,
  digestHex: digestHex,
);

/// Generate circuit binary files for ZK proof generation.
///
/// This is a long-running operation (10-30 minutes) that generates the
/// circuit binaries needed for wormhole withdrawal proofs.
///
/// # Arguments
/// * `output_dir` - Directory to write the binaries to
/// * `num_leaf_proofs` - Number of leaf proofs per aggregation (typically 8)
///
/// # Returns
/// A `CircuitGenerationResult` indicating success or failure.
///
/// # Generated Files
/// - `prover.bin` - Prover circuit data (~163MB)
/// - `common.bin` - Common circuit data
/// - `verifier.bin` - Verifier circuit data
/// - `dummy_proof.bin` - Dummy proof for aggregation padding
/// - `aggregated_common.bin` - Aggregated circuit common data
/// - `aggregated_verifier.bin` - Aggregated circuit verifier data
/// - `config.json` - Configuration with hashes for integrity verification
Future<CircuitGenerationResult> generateCircuitBinaries({
  required String outputDir,
  required int numLeafProofs,
}) => RustLib.instance.api.crateApiWormholeGenerateCircuitBinaries(
  outputDir: outputDir,
  numLeafProofs: numLeafProofs,
);

/// Check if circuit binaries exist and are valid in a directory.
///
/// # Arguments
/// * `bins_dir` - Directory containing the circuit binaries
///
/// # Returns
/// True if all required files exist, false otherwise.
bool checkCircuitBinariesExist({required String binsDir}) => RustLib
    .instance
    .api
    .crateApiWormholeCheckCircuitBinariesExist(binsDir: binsDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WormholeProofAggregator>>
abstract class WormholeProofAggregator implements RustOpaqueInterface {
  /// Add a proof to the aggregation buffer.
  ///
  /// # Arguments
  /// * `proof_hex` - The serialized proof bytes (hex encoded with 0x prefix)
  Future<void> addProof({required String proofHex});

  /// Aggregate all proofs in the buffer.
  ///
  /// If fewer than `batch_size` proofs have been added, the remaining
  /// slots are filled with dummy proofs automatically.
  ///
  /// # Returns
  /// The aggregated proof.
  Future<AggregatedProof> aggregate();

  /// Get the batch size (number of proofs per aggregation).
  Future<BigInt> batchSize();

  /// Clear the proof buffer without aggregating.
  ///
  /// Note: The new Layer0Aggregator API doesn't support clearing the buffer
  /// directly. To clear, you need to create a new aggregator instance.
  Future<void> clear();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new proof aggregator from circuit files.
  ///
  /// # Arguments
  /// * `bins_dir` - Path to directory containing aggregator circuit files
  ///
  /// # Returns
  /// A new proof aggregator instance.
  static Future<WormholeProofAggregator> newInstance({
    required String binsDir,
  }) => RustLib.instance.api.crateApiWormholeWormholeProofAggregatorNew(
    binsDir: binsDir,
  );

  /// Get the number of proofs currently in the buffer.
  Future<BigInt> proofCount();
}

/// Result of proof aggregation.
class AggregatedProof {
  /// The serialized aggregated proof bytes (hex encoded).
  final String proofHex;

  /// Number of real proofs in the batch (rest are dummies).
  final BigInt numRealProofs;

  const AggregatedProof({required this.proofHex, required this.numRealProofs});

  @override
  int get hashCode => proofHex.hashCode ^ numRealProofs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AggregatedProof &&
          runtimeType == other.runtimeType &&
          proofHex == other.proofHex &&
          numRealProofs == other.numRealProofs;
}

/// Block header data needed for proof generation.
class BlockHeaderData {
  /// Parent block hash (hex encoded).
  final String parentHashHex;

  /// State root of the block (hex encoded).
  final String stateRootHex;

  /// Extrinsics root of the block (hex encoded).
  final String extrinsicsRootHex;

  /// Block number.
  final int blockNumber;

  /// Encoded digest (hex encoded, up to 110 bytes).
  final String digestHex;

  const BlockHeaderData({
    required this.parentHashHex,
    required this.stateRootHex,
    required this.extrinsicsRootHex,
    required this.blockNumber,
    required this.digestHex,
  });

  @override
  int get hashCode =>
      parentHashHex.hashCode ^
      stateRootHex.hashCode ^
      extrinsicsRootHex.hashCode ^
      blockNumber.hashCode ^
      digestHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockHeaderData &&
          runtimeType == other.runtimeType &&
          parentHashHex == other.parentHashHex &&
          stateRootHex == other.stateRootHex &&
          extrinsicsRootHex == other.extrinsicsRootHex &&
          blockNumber == other.blockNumber &&
          digestHex == other.digestHex;
}

/// Configuration loaded from circuit binaries directory.
class CircuitConfig {
  /// Number of leaf proofs in an aggregation batch.
  final BigInt numLeafProofs;

  const CircuitConfig({required this.numLeafProofs});

  /// Load configuration from a circuit binaries directory.
  static Future<CircuitConfig> load({required String binsDir}) =>
      RustLib.instance.api.crateApiWormholeCircuitConfigLoad(binsDir: binsDir);

  @override
  int get hashCode => numLeafProofs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CircuitConfig &&
          runtimeType == other.runtimeType &&
          numLeafProofs == other.numLeafProofs;
}

/// Result of circuit binary generation
class CircuitGenerationResult {
  /// Whether generation succeeded
  final bool success;

  /// Error message if failed
  final String? error;

  /// Path to the generated binaries directory
  final String? outputDir;

  const CircuitGenerationResult({
    required this.success,
    this.error,
    this.outputDir,
  });

  @override
  int get hashCode => success.hashCode ^ error.hashCode ^ outputDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CircuitGenerationResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error &&
          outputDir == other.outputDir;
}

/// Result of proof generation.
class GeneratedProof {
  /// The serialized proof bytes (hex encoded).
  final String proofHex;

  /// The nullifier for this UTXO (hex encoded) - used to track spent UTXOs.
  final String nullifierHex;

  const GeneratedProof({required this.proofHex, required this.nullifierHex});

  @override
  int get hashCode => proofHex.hashCode ^ nullifierHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedProof &&
          runtimeType == other.runtimeType &&
          proofHex == other.proofHex &&
          nullifierHex == other.nullifierHex;
}

/// Output assignment for a proof - where the funds go.
class ProofOutputAssignment {
  /// Amount for output 1 (quantized to 2 decimal places).
  final int outputAmount1;

  /// Exit account for output 1 (SS58 address).
  final String exitAccount1;

  /// Amount for output 2 (quantized, 0 if unused).
  final int outputAmount2;

  /// Exit account for output 2 (SS58 address, empty if unused).
  final String exitAccount2;

  const ProofOutputAssignment({
    required this.outputAmount1,
    required this.exitAccount1,
    required this.outputAmount2,
    required this.exitAccount2,
  });

  @override
  int get hashCode =>
      outputAmount1.hashCode ^
      exitAccount1.hashCode ^
      outputAmount2.hashCode ^
      exitAccount2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProofOutputAssignment &&
          runtimeType == other.runtimeType &&
          outputAmount1 == other.outputAmount1 &&
          exitAccount1 == other.exitAccount1 &&
          outputAmount2 == other.outputAmount2 &&
          exitAccount2 == other.exitAccount2;
}

/// Error type for wormhole operations
class WormholeError implements FrbException {
  final String message;

  const WormholeError({required this.message});

  /// Returns the error message as a string for display.
  @override
  String toString() => RustLib.instance.api
      .crateApiWormholeWormholeErrorToDisplayString(that: this);

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Result of wormhole pair derivation
class WormholePairResult {
  /// The wormhole address as SS58 (the on-chain account)
  final String address;

  /// The raw address bytes (32 bytes, hex encoded)
  final String addressHex;

  /// The first hash / rewards inner hash as SS58 (pass to --rewards-inner-hash)
  final String firstHashSs58;

  /// The first hash / rewards preimage bytes (32 bytes, hex encoded)
  final String firstHashHex;

  /// The secret bytes (32 bytes, hex encoded) - SENSITIVE, needed for ZK proofs
  final String secretHex;

  const WormholePairResult({
    required this.address,
    required this.addressHex,
    required this.firstHashSs58,
    required this.firstHashHex,
    required this.secretHex,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      addressHex.hashCode ^
      firstHashSs58.hashCode ^
      firstHashHex.hashCode ^
      secretHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholePairResult &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          addressHex == other.addressHex &&
          firstHashSs58 == other.firstHashSs58 &&
          firstHashHex == other.firstHashHex &&
          secretHex == other.secretHex;
}

/// Opaque handle to a proof generator.
///
/// The generator is expensive to initialize (loads ~171MB of circuit data),
/// so it should be created once and reused for all proof generations.
class WormholeProofGenerator {
  final String binsDir;

  const WormholeProofGenerator({required this.binsDir});

  /// Generate a proof for a wormhole withdrawal.
  ///
  /// This function delegates to quantus-cli's wormhole_lib to ensure
  /// the proof generation logic is identical to the CLI.
  ///
  /// # Arguments
  /// * `utxo` - The UTXO to spend (with leaf_index and input_amount)
  /// * `output` - Where to send the funds
  /// * `fee_bps` - Fee in basis points
  /// * `block_header` - Block header for the proof
  /// * `zk_merkle_proof` - ZK Merkle proof for the transfer
  ///
  /// # Returns
  /// The generated proof and nullifier.
  Future<GeneratedProof> generateProof({
    required WormholeUtxo utxo,
    required ProofOutputAssignment output,
    required int feeBps,
    required BlockHeaderData blockHeader,
    required ZkMerkleProofData zkMerkleProof,
  }) =>
      RustLib.instance.api.crateApiWormholeWormholeProofGeneratorGenerateProof(
        that: this,
        utxo: utxo,
        output: output,
        feeBps: feeBps,
        blockHeader: blockHeader,
        zkMerkleProof: zkMerkleProof,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new proof generator from circuit files.
  ///
  /// # Arguments
  /// * `bins_dir` - Path to directory containing prover.bin and common.bin
  ///
  /// # Returns
  /// A new proof generator instance.
  static Future<WormholeProofGenerator> newInstance({
    required String binsDir,
  }) => RustLib.instance.api.crateApiWormholeWormholeProofGeneratorNew(
    binsDir: binsDir,
  );

  @override
  int get hashCode => binsDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeProofGenerator &&
          runtimeType == other.runtimeType &&
          binsDir == other.binsDir;
}

/// A wormhole UTXO (unspent transaction output) - FFI-friendly version.
///
/// Represents an unspent wormhole deposit that can be used as input
/// for generating a proof.
class WormholeUtxo {
  /// The secret used to derive the wormhole address (hex encoded with 0x prefix).
  final String secretHex;

  /// Input amount (quantized to 2 decimal places, as stored in ZK leaf).
  final int inputAmount;

  /// Transfer count from the NativeTransferred event.
  final BigInt transferCount;

  /// Leaf index in the ZK tree.
  final BigInt leafIndex;

  /// Block hash where the proof is anchored - hex encoded.
  final String blockHashHex;

  const WormholeUtxo({
    required this.secretHex,
    required this.inputAmount,
    required this.transferCount,
    required this.leafIndex,
    required this.blockHashHex,
  });

  @override
  int get hashCode =>
      secretHex.hashCode ^
      inputAmount.hashCode ^
      transferCount.hashCode ^
      leafIndex.hashCode ^
      blockHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeUtxo &&
          runtimeType == other.runtimeType &&
          secretHex == other.secretHex &&
          inputAmount == other.inputAmount &&
          transferCount == other.transferCount &&
          leafIndex == other.leafIndex &&
          blockHashHex == other.blockHashHex;
}

/// ZK Merkle proof data for the transfer.
class ZkMerkleProofData {
  /// ZK tree root from block header (hex encoded, 32 bytes).
  final String zkTreeRootHex;

  /// Leaf hash (hex encoded, 32 bytes).
  final String leafHashHex;

  /// Unsorted sibling hashes at each level (3 siblings per level, each hex encoded).
  /// Outer vec = levels, inner vec = 3 siblings per level.
  final List<List<String>> siblingsHex;

  const ZkMerkleProofData({
    required this.zkTreeRootHex,
    required this.leafHashHex,
    required this.siblingsHex,
  });

  @override
  int get hashCode =>
      zkTreeRootHex.hashCode ^ leafHashHex.hashCode ^ siblingsHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZkMerkleProofData &&
          runtimeType == other.runtimeType &&
          zkTreeRootHex == other.zkTreeRootHex &&
          leafHashHex == other.leafHashHex &&
          siblingsHex == other.siblingsHex;
}
