// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `all_required_files_exist`, `leaf_files_exist`, `log_mem`, `process_memory`, `read_task_vm_info`, `vec_to_32`, `vec_to_digest`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TaskVmInfoRev1`

String computeAddressHashHex({required List<int> rawAddress}) =>
    RustLib.instance.api.crateApiWormholeComputeAddressHashHex(rawAddress: rawAddress);

Uint8List computeNullifier({required List<int> secret, required BigInt transferCount}) =>
    RustLib.instance.api.crateApiWormholeComputeNullifier(secret: secret, transferCount: transferCount);

Uint8List computeWormholeAddress({required List<int> secret}) =>
    RustLib.instance.api.crateApiWormholeComputeWormholeAddress(secret: secret);

int wormholeComputeOutputAmount({required int inputAmount, required int feeBps}) =>
    RustLib.instance.api.crateApiWormholeWormholeComputeOutputAmount(inputAmount: inputAmount, feeBps: feeBps);

int decodeLeafAmount({required List<int> leafData}) =>
    RustLib.instance.api.crateApiWormholeDecodeLeafAmount(leafData: leafData);

BigInt decodeLeafTransferCount({required List<int> leafData}) =>
    RustLib.instance.api.crateApiWormholeDecodeLeafTransferCount(leafData: leafData);

Uint8List decodeLeafToAccount({required List<int> leafData}) =>
    RustLib.instance.api.crateApiWormholeDecodeLeafToAccount(leafData: leafData);

MerkleProcessed computeMerklePositions({
  required List<int> unsortedSiblingsFlat,
  required List<int> leafHash,
  required int depth,
}) => RustLib.instance.api.crateApiWormholeComputeMerklePositions(
  unsortedSiblingsFlat: unsortedSiblingsFlat,
  leafHash: leafHash,
  depth: depth,
);

Future<String> ensureCircuitBinaries({required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeEnsureCircuitBinaries(binsDir: binsDir);

/// Lightweight variant that only generates leaf circuit binaries (prover.bin,
/// common.bin, verifier.bin, dummy_proof.bin). Skips the heavy aggregation
/// circuit generation entirely. Use with `aggregate_proofs_fresh` which builds
/// the aggregation circuit in memory at proving time.
Future<void> ensureLeafCircuitBinaries({required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeEnsureLeafCircuitBinaries(binsDir: binsDir);

Future<ProofOutput> generateProof({
  required ProofInput input,
  required String proverBinPath,
  required String commonBinPath,
}) => RustLib.instance.api.crateApiWormholeGenerateProof(
  input: input,
  proverBinPath: proverBinPath,
  commonBinPath: commonBinPath,
);

Future<Uint8List> aggregateProofs({required List<Uint8List> proofBytesList, required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeAggregateProofs(proofBytesList: proofBytesList, binsDir: binsDir);

/// Dump every field of task_vm_info for deep debugging. Call sparingly.
Future<void> logMemDetailed({required String tag}) => RustLib.instance.api.crateApiWormholeLogMemDetailed(tag: tag);

/// Returns (phys_footprint_bytes, virtual_bytes). Useful for Dart-side polling.
(BigInt, BigInt) getProcessMemory() => RustLib.instance.api.crateApiWormholeGetProcessMemory();

/// Returns (phys_footprint, resident_size, compressed). Dart-side memory probe.
(BigInt, BigInt, BigInt) getProcessMemoryDetailed() => RustLib.instance.api.crateApiWormholeGetProcessMemoryDetailed();

/// Dart-side hook to dump every memory field.
void logMemorySnapshot({required String tag}) => RustLib.instance.api.crateApiWormholeLogMemorySnapshot(tag: tag);

/// Force the system allocator (Apple libmalloc) to return freed pages to the OS.
/// On other platforms this is a no-op.
/// Apple's malloc keeps freed memory in per-zone caches by default; after a heavy
/// allocation phase like ZK proving this can leave 100s of MB of dirty pages.
/// We iterate every registered zone — passing `null` only reaches the default
/// zone, which is NOT where Rust's allocator lives, so calling on null released
/// 0 bytes in practice.
Future<void> releaseMemory() => RustLib.instance.api.crateApiWormholeReleaseMemory();

/// Limit rayon parallelism to reduce peak memory during proving.
/// Plonky2 multiplies its per-thread FFT buffers by the rayon pool size, so
/// fewer threads = lower peak memory (at the cost of wall-clock time).
/// Idempotent / safe to call repeatedly; only the first call wins.
Future<void> setProvingThreadCount({required int numThreads}) =>
    RustLib.instance.api.crateApiWormholeSetProvingThreadCount(numThreads: numThreads);

Future<Uint8List> aggregateProofsFresh({required List<Uint8List> proofBytesList, required String binsDir}) =>
    RustLib.instance.api.crateApiWormholeAggregateProofsFresh(proofBytesList: proofBytesList, binsDir: binsDir);

class MerkleProcessed {
  final Uint8List sortedSiblingsFlat;
  final Uint8List positions;

  const MerkleProcessed({required this.sortedSiblingsFlat, required this.positions});

  @override
  int get hashCode => sortedSiblingsFlat.hashCode ^ positions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MerkleProcessed &&
          runtimeType == other.runtimeType &&
          sortedSiblingsFlat == other.sortedSiblingsFlat &&
          positions == other.positions;
}

class ProofInput {
  final Uint8List secret;
  final BigInt transferCount;
  final Uint8List wormholeAddress;
  final int inputAmount;
  final Uint8List blockHash;
  final int blockNumber;
  final Uint8List parentHash;
  final Uint8List stateRoot;
  final Uint8List extrinsicsRoot;
  final Uint8List digest;
  final Uint8List zkTreeRoot;
  final Uint8List sortedSiblingsFlat;
  final Uint8List positions;
  final Uint8List exitAccount1;
  final int outputAmount1;
  final int volumeFeeBps;
  final int assetId;

  const ProofInput({
    required this.secret,
    required this.transferCount,
    required this.wormholeAddress,
    required this.inputAmount,
    required this.blockHash,
    required this.blockNumber,
    required this.parentHash,
    required this.stateRoot,
    required this.extrinsicsRoot,
    required this.digest,
    required this.zkTreeRoot,
    required this.sortedSiblingsFlat,
    required this.positions,
    required this.exitAccount1,
    required this.outputAmount1,
    required this.volumeFeeBps,
    required this.assetId,
  });

  @override
  int get hashCode =>
      secret.hashCode ^
      transferCount.hashCode ^
      wormholeAddress.hashCode ^
      inputAmount.hashCode ^
      blockHash.hashCode ^
      blockNumber.hashCode ^
      parentHash.hashCode ^
      stateRoot.hashCode ^
      extrinsicsRoot.hashCode ^
      digest.hashCode ^
      zkTreeRoot.hashCode ^
      sortedSiblingsFlat.hashCode ^
      positions.hashCode ^
      exitAccount1.hashCode ^
      outputAmount1.hashCode ^
      volumeFeeBps.hashCode ^
      assetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProofInput &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          transferCount == other.transferCount &&
          wormholeAddress == other.wormholeAddress &&
          inputAmount == other.inputAmount &&
          blockHash == other.blockHash &&
          blockNumber == other.blockNumber &&
          parentHash == other.parentHash &&
          stateRoot == other.stateRoot &&
          extrinsicsRoot == other.extrinsicsRoot &&
          digest == other.digest &&
          zkTreeRoot == other.zkTreeRoot &&
          sortedSiblingsFlat == other.sortedSiblingsFlat &&
          positions == other.positions &&
          exitAccount1 == other.exitAccount1 &&
          outputAmount1 == other.outputAmount1 &&
          volumeFeeBps == other.volumeFeeBps &&
          assetId == other.assetId;
}

class ProofOutput {
  final Uint8List proofBytes;
  final Uint8List nullifier;

  const ProofOutput({required this.proofBytes, required this.nullifier});

  @override
  int get hashCode => proofBytes.hashCode ^ nullifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProofOutput &&
          runtimeType == other.runtimeType &&
          proofBytes == other.proofBytes &&
          nullifier == other.nullifier;
}
