include: package:lints/recommended.yaml

# Additional lint rules to maintain code quality
linter:
  rules:
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - avoid_redundant_argument_values
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_super_parameters
    - require_trailing_commas

formatter:
  page_width: 120

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false 