name: resonance_network_wallet
description: A Flutter wallet for the Quantus blockchain.
publish_to: "none"

version: 1.1.5+67

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  quantus_sdk:
  video_player:
  qr_flutter:
  flutter_svg:
  mobile_scanner:
  flutter_native_splash:
  cupertino_icons:
  flash:
  flutter_launcher_icons:
  local_auth: ^2.1.6

  decimal:
  hex:
  base32: ^2.0.0
  ss58:
  bip39_mnemonic:
  intl:
  quiver:
  convert:
  crypto:

  shared_preferences:
  flutter_secure_storage:
  http:

  human_checksum:
    git:
      url: https://github.com/Quantus-Network/qp-human-checkphrase.git
      ref: v1.1.0
      path: dart
  provider: ^6.1.5
  polkadart: ^0.7.3
  share_plus: ^12.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  telemetrydecksdk: ^3.0.0
  async: ^2.13.0
  app_links: ^6.4.1
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.2
  play_install_referrer: ^0.5.0
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  mockito: ^5.4.6
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/text/crypto_checksum_bip39.txt
    - assets/send_icon.png
    - assets/receive_icon.png
    - assets/swap_icon_1.svg
    - assets/scan_1.svg
    - assets/paste_icon_1.svg
    - assets/active_dot.png
    - assets/receive_line.svg
    - assets/bridge_icon.svg
    - assets/quantus_logo.svg
    - assets/hourglass.svg
    - assets/settings_icon_off.svg
    - assets/navbar/
    - assets/notification/
    - assets/videos/
    - assets/transaction/
    - assets/logo/
    - assets/send_btn_decoration.png
    - assets/receive_btn_decoration.png
    - assets/qq-logo.png
    - assets/navbar/qcat_navbar_icon.png
    - assets/notification/notification_top_icon.png
    - assets/high_security/security_icon_big.svg
    - assets/high_security/step_indicator_active_icon.svg
    - assets/high_security/step_indicator_icon.svg
    - assets/high_security/big_red_button_icon.png
    - assets/high_security/intercept_icon.svg
    - assets/quests/quests_top_logo.png

  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 100
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700

# Add flutter_native_splash configuration section
flutter_native_splash:
  image: assets/splash.png
  color: "#000000"
  android_gravity: center
  android: true
  ios: true

  # Optional: Configure Android 12 splash screen specific settings
  android_12:
    icon_background_color: "#000000"
