name: resonance_network_wallet
description: A Flutter wallet for the Quantus blockchain.
publish_to: 'none'

version: 1.0.0+16

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  quantus_sdk:
  video_player:
  qr_flutter:
  flutter_svg:
  mobile_scanner:
  flutter_native_splash:
  cupertino_icons:
  flash:
  flutter_launcher_icons:
  
  decimal:
  hex:
  ss58:
  bip39_mnemonic:
  intl:
  quiver:
  convert:
  crypto:
  
  shared_preferences:
  flutter_secure_storage:
  http:
  
  human_checksum:
    git:
      url: https://github.com/Quantus-Network/human-checkphrase.git
      path: dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  test:
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/light_leak_effect_background.jpg
    - assets/text/crypto_checksum_bip39.txt
    - assets/send_icon.png
    - assets/send_icon_1.svg
    - assets/receive_icon.png
    - assets/receive_icon.svg
    - assets/swap_icon.svg
    - assets/scan.svg
    - assets/main_wallet_title_logo.svg
    - assets/account_list_icon.svg
    - assets/res_icon.svg
    - assets/intro_bg_video.mp4
    - assets/paste_icon.svg
    - assets/active_dot.png
    - assets/send_line.svg
    - assets/receive_line.svg
    - assets/bridge_icon.svg
    - assets/quantus_logo.svg
    - assets/quantus_logo_hz.svg
    - assets/stop_icon.svg

  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 100
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700

# Add flutter_native_splash configuration section
flutter_native_splash:
  # Replace color with background_image
  # color: "#0E0E0E" 
  background_image: "assets/light_leak_effect_background.jpg"
  # image: assets/logo.png # You can still add a logo on top if desired

  # Optional: Configure Android 12 splash screen specific settings
  android_12:
    # Replace color with background_image
    # color: "#0E0E0E"
    background_image: "assets/light_leak_effect_background.jpg"
    # image: assets/logo.png

  # Optional: Set color for status bar and navigation bar (Android)
  # color_dark: "#0E0E0E"
  # status_bar_color_dark: "#0E0E0E" # Match status bar to background
  # navigation_bar_color_dark: "#0E0E0E" # Match navigation bar to background

  # Optional: Set status bar style for iOS (dark content on light background or vice-versa)
  # ios_content_mode: "dark" 