name: quantus_miner
description: Quantus PoW miner (desktop / mobile)
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  path: ^1.9.1
  quantus_sdk:
    path: ../quantus_sdk
  flutter_secure_storage: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ^2.9.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  another_flushbar: ^1.10.2
  go_router: ^14.1.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.5.0
  decimal: ^2.3.3
  permission_handler: ^11.1.0
  image_picker: ^1.1.2
  logger: ^2.5.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
