name: quantus_miner
description: Quantus PoW miner (desktop / mobile)
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  quantus_sdk:
    path: ../quantus_sdk
