// Mocks generated by Mockito 5.4.6 from annotations
// in resonance_network_wallet/test/unit/wallet_creation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:quantus_sdk/quantus_sdk.dart' as _i4;
import 'package:quantus_sdk/src/models/account.dart' as _i2;
import 'package:quantus_sdk/src/models/display_account.dart' as _i6;
import 'package:resonance_network_wallet/services/referral_service.dart' as _i8;
import 'package:share_plus/share_plus.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccount_0 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeShareParams_1 extends _i1.SmartFake implements _i3.ShareParams {
  _FakeShareParams_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i4.SettingsService {
  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Account>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i5.Future<List<_i2.Account>>.value(<_i2.Account>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Account>>.value(<_i2.Account>[]),
          )
          as _i5.Future<List<_i2.Account>>);

  @override
  _i5.Future<void> saveAccounts(List<_i2.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccounts, [accounts]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAccountsToMigrate(List<_i2.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#setAccountsToMigrate, [accounts]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i2.Account> getAccountsToMigrate() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsToMigrate, []),
            returnValue: <_i2.Account>[],
            returnValueForMissingStub: <_i2.Account>[],
          )
          as List<_i2.Account>);

  @override
  _i5.Future<void> clearAccountsToMigrate() =>
      (super.noSuchMethod(
            Invocation.method(#clearAccountsToMigrate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addAccount(_i2.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateAccount(_i2.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeAccount(_i2.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setActiveAccount(_i6.DisplayAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.DisplayAccount?> getActiveAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAccount, []),
            returnValue: _i5.Future<_i6.DisplayAccount?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.DisplayAccount?>.value(),
          )
          as _i5.Future<_i6.DisplayAccount?>);

  @override
  _i5.Future<_i2.Account?> getActiveRegularAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRegularAccount, []),
            returnValue: _i5.Future<_i2.Account?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Account?>.value(),
          )
          as _i5.Future<_i2.Account?>);

  @override
  _i5.Future<_i2.Account?> getAccount({required int? walletIndex, required int? index}) =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, [], {#walletIndex: walletIndex, #index: index}),
            returnValue: _i5.Future<_i2.Account?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Account?>.value(),
          )
          as _i5.Future<_i2.Account?>);

  @override
  _i5.Future<int> getNextFreeAccountIndex(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getNextFreeAccountIndex, [walletIndex]),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<Map<String, String>> getAddressBook() =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBook, []),
            returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
            returnValueForMissingStub: _i5.Future<Map<String, String>>.value(<String, String>{}),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> saveAddressBook(Map<String, String>? addressBook) =>
      (super.noSuchMethod(
            Invocation.method(#saveAddressBook, [addressBook]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAddressName(String? address, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setAddressName, [address, name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAddressName(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressName, [address]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> removeAddressName(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#removeAddressName, [address]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> getHasWallet() =>
      (super.noSuchMethod(
            Invocation.method(#getHasWallet, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isWalletLoggedOut() =>
      (super.noSuchMethod(
            Invocation.method(#isWalletLoggedOut, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  String getMnemonicKey(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getMnemonicKey, [walletIndex]),
            returnValue: _i7.dummyValue<String>(this, Invocation.method(#getMnemonicKey, [walletIndex])),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.method(#getMnemonicKey, [walletIndex])),
          )
          as String);

  @override
  _i5.Future<void> setMnemonic(String? mnemonic, int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#setMnemonic, [mnemonic, walletIndex]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getMnemonic(int? walletIndex) =>
      (super.noSuchMethod(
            Invocation.method(#getMnemonic, [walletIndex]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setReversibleEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setReversibleEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isReversibleEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isReversibleEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setReversibleTimeSeconds(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setReversibleTimeSeconds, [seconds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int?> getReversibleTimeSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#getReversibleTimeSeconds, []),
            returnValue: _i5.Future<int?>.value(),
            returnValueForMissingStub: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<void> setBalanceHidden(bool? hidden) =>
      (super.noSuchMethod(
            Invocation.method(#setBalanceHidden, [hidden]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isBalanceHidden() =>
      (super.noSuchMethod(Invocation.method(#isBalanceHidden, []), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  _i5.Future<void> setCurrencyFlipped(bool? flipped) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrencyFlipped, [flipped]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isCurrencyFlipped() =>
      (super.noSuchMethod(
            Invocation.method(#isCurrencyFlipped, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setSelectedFiatCurrency(String? currencyCode) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedFiatCurrency, [currencyCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setPosModeEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setPosModeEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isPosModeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isPosModeEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key]), returnValueForMissingStub: null) as bool?);

  @override
  _i5.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key]), returnValueForMissingStub: null) as String?);

  @override
  _i5.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setLastPausedTime(DateTime? time) =>
      super.noSuchMethod(Invocation.method(#setLastPausedTime, [time]), returnValueForMissingStub: null);

  @override
  void cleanLastPausedTime() =>
      super.noSuchMethod(Invocation.method(#cleanLastPausedTime, []), returnValueForMissingStub: null);

  @override
  bool hasOldAccounts() =>
      (super.noSuchMethod(Invocation.method(#hasOldAccounts, []), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  List<_i2.Account> getOldAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getOldAccounts, []),
            returnValue: <_i2.Account>[],
            returnValueForMissingStub: <_i2.Account>[],
          )
          as List<_i2.Account>);

  @override
  _i5.Future<void> clearOldAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#clearOldAccounts, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setOldAccountsData(String? jsonData) =>
      (super.noSuchMethod(
            Invocation.method(#setOldAccountsData, [jsonData]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void resetForTest() => super.noSuchMethod(Invocation.method(#resetForTest, []), returnValueForMissingStub: null);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool referralCheckCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#referralCheckCompleted, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setReferralCheckCompleted() =>
      super.noSuchMethod(Invocation.method(#setReferralCheckCompleted, []), returnValueForMissingStub: null);

  @override
  void clearReferralCheckCompletedFlag() =>
      super.noSuchMethod(Invocation.method(#clearReferralCheckCompletedFlag, []), returnValueForMissingStub: null);

  @override
  void setReferralCode(String? code) =>
      super.noSuchMethod(Invocation.method(#setReferralCode, [code]), returnValueForMissingStub: null);

  @override
  bool hasWatchedQuestsPromo() =>
      (super.noSuchMethod(
            Invocation.method(#hasWatchedQuestsPromo, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setQuestsPromoWatched() =>
      super.noSuchMethod(Invocation.method(#setQuestsPromoWatched, []), returnValueForMissingStub: null);

  @override
  void clearQuestsPromoWatchedFlag() =>
      super.noSuchMethod(Invocation.method(#clearQuestsPromoWatchedFlag, []), returnValueForMissingStub: null);

  @override
  bool existingUserSeenPromoVideo() =>
      (super.noSuchMethod(
            Invocation.method(#existingUserSeenPromoVideo, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setExistingUserSeenPromoVideo() =>
      super.noSuchMethod(Invocation.method(#setExistingUserSeenPromoVideo, []), returnValueForMissingStub: null);

  @override
  void clearExistingUserSeenPromoVideoFlag() =>
      super.noSuchMethod(Invocation.method(#clearExistingUserSeenPromoVideoFlag, []), returnValueForMissingStub: null);
}

/// A class which mocks [AccountsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountsService extends _i1.Mock implements _i4.AccountsService {
  @override
  set onAccountsChanged(void Function()? _onAccountsChanged) =>
      super.noSuchMethod(Invocation.setter(#onAccountsChanged, _onAccountsChanged), returnValueForMissingStub: null);

  @override
  _i5.Future<_i2.Account> createNewAccount({required int? walletIndex}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewAccount, [], {#walletIndex: walletIndex}),
            returnValue: _i5.Future<_i2.Account>.value(
              _FakeAccount_0(this, Invocation.method(#createNewAccount, [], {#walletIndex: walletIndex})),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Account>.value(
              _FakeAccount_0(this, Invocation.method(#createNewAccount, [], {#walletIndex: walletIndex})),
            ),
          )
          as _i5.Future<_i2.Account>);

  @override
  _i5.Future<void> updateAccountName(_i2.Account? account, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccountName, [account, name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addAccount(_i2.Account? newAccount) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [newAccount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Account>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i5.Future<List<_i2.Account>>.value(<_i2.Account>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Account>>.value(<_i2.Account>[]),
          )
          as _i5.Future<List<_i2.Account>>);

  @override
  _i5.Future<void> removeAccount(_i2.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [account]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ReferralService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReferralService extends _i1.Mock implements _i8.ReferralService {
  @override
  _i5.Future<void> checkPlayStoreReferralCode() =>
      (super.noSuchMethod(
            Invocation.method(#checkPlayStoreReferralCode, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> optInRewardProgram() =>
      (super.noSuchMethod(
            Invocation.method(#optInRewardProgram, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getReferralData() =>
      (super.noSuchMethod(
            Invocation.method(#getReferralData, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  void invalidateCache() =>
      super.noSuchMethod(Invocation.method(#invalidateCache, []), returnValueForMissingStub: null);

  @override
  _i5.Future<bool> getRewardProgramParticiation() =>
      (super.noSuchMethod(
            Invocation.method(#getRewardProgramParticiation, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> submitReferralToBackend({required String? referral}) =>
      (super.noSuchMethod(
            Invocation.method(#submitReferralToBackend, [], {#referral: referral}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> submitAddressToBackend() =>
      (super.noSuchMethod(
            Invocation.method(#submitAddressToBackend, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String generateReferralLink(String? referralCode) =>
      (super.noSuchMethod(
            Invocation.method(#generateReferralLink, [referralCode]),
            returnValue: _i7.dummyValue<String>(this, Invocation.method(#generateReferralLink, [referralCode])),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateReferralLink, [referralCode]),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.Account> getMainAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getMainAccount, []),
            returnValue: _i5.Future<_i2.Account>.value(_FakeAccount_0(this, Invocation.method(#getMainAccount, []))),
            returnValueForMissingStub: _i5.Future<_i2.Account>.value(
              _FakeAccount_0(this, Invocation.method(#getMainAccount, [])),
            ),
          )
          as _i5.Future<_i2.Account>);

  @override
  _i5.Future<String> getMyInviteCode() =>
      (super.noSuchMethod(
            Invocation.method(#getMyInviteCode, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getMyInviteCode, [])),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getMyInviteCode, [])),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.ShareParams> getShareLinkParameters(_i9.Rect? positionOrigin) =>
      (super.noSuchMethod(
            Invocation.method(#getShareLinkParameters, [positionOrigin]),
            returnValue: _i5.Future<_i3.ShareParams>.value(
              _FakeShareParams_1(this, Invocation.method(#getShareLinkParameters, [positionOrigin])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ShareParams>.value(
              _FakeShareParams_1(this, Invocation.method(#getShareLinkParameters, [positionOrigin])),
            ),
          )
          as _i5.Future<_i3.ShareParams>);
}
