include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_single_quotes

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    avoid_print: ignore # print is the most reliable way to debug the app
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
