name: quantus_miner
description: Quantus PoW miner (desktop / mobile)
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Workspace packages (managed by melos.yaml)
  quantus_sdk: # Version managed by melos.yaml
  
  # Networking and storage
  http: # Version managed by melos.yaml
  shared_preferences: # Version managed by melos.yaml
  flutter_secure_storage: # Version managed by melos.yaml
  
  # State management and architecture
  provider: # Version managed by melos.yaml
  hooks_riverpod: # Version managed by melos.yaml
  flutter_hooks: # Version managed by melos.yaml
  go_router: # Version managed by melos.yaml
  
  # UI and utilities
  another_flushbar: # Version managed by melos.yaml
  flutter_svg: # Version managed by melos.yaml
  
  # System and file operations
  path: # Version managed by melos.yaml
  path_provider: # Version managed by melos.yaml
  permission_handler: # Version managed by melos.yaml
  image_picker: # Version managed by melos.yaml
  
  # Math and logging
  decimal: # Version managed by melos.yaml
  logger: # Version managed by melos.yaml

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: # Version managed by melos.yaml
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/quantus_icon.svg
  