// // Mocks generated by Mockito 5.4.6 from annotations
// // in resonance_network_wallet/test/widget/send_screen_widget_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i3;
// import 'dart:typed_data' as _i5;

// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i6;
// import 'package:polkadart/polkadart.dart' as _i8;
// import 'package:quantus_sdk/generated/schrodinger/types/pallet_reversible_transfers/high_security_account_data.dart'
//     as _i9;
// import 'package:quantus_sdk/generated/schrodinger/types/pallet_reversible_transfers/pending_transfer.dart' as _i10;
// import 'package:quantus_sdk/generated/schrodinger/types/qp_scheduler/block_number_or_timestamp.dart' as _i7;
// import 'package:quantus_sdk/quantus_sdk.dart' as _i2;
// import 'package:quantus_sdk/src/models/account.dart' as _i4;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeKeypair_0 extends _i1.SmartFake implements _i2.Keypair {
//   _FakeKeypair_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
// }

// class _FakeExtrinsicFeeData_1 extends _i1.SmartFake implements _i2.ExtrinsicFeeData {
//   _FakeExtrinsicFeeData_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
// }

// class _FakeExtrinsicData_2 extends _i1.SmartFake implements _i2.ExtrinsicData {
//   _FakeExtrinsicData_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
// }

// class _FakeBalances_3 extends _i1.SmartFake implements _i2.Balances {
//   _FakeBalances_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
// }

// class _FakeReversibleTransfers_4 extends _i1.SmartFake implements _i2.ReversibleTransfers {
//   _FakeReversibleTransfers_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
// }

// /// A class which mocks [SettingsService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockSettingsService extends _i1.Mock implements _i2.SettingsService {
//   MockSettingsService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<void> initialize() =>
//       (super.noSuchMethod(
//             Invocation.method(#initialize, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<List<_i4.Account>> getAccounts() =>
//       (super.noSuchMethod(
//             Invocation.method(#getAccounts, []),
//             returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
//           )
//           as _i3.Future<List<_i4.Account>>);

//   @override
//   _i3.Future<void> saveAccounts(List<_i4.Account>? accounts) =>
//       (super.noSuchMethod(
//             Invocation.method(#saveAccounts, [accounts]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> setAccountsToMigrate(List<_i4.Account>? accounts) =>
//       (super.noSuchMethod(
//             Invocation.method(#setAccountsToMigrate, [accounts]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   List<_i4.Account> getAccountsToMigrate() =>
//       (super.noSuchMethod(Invocation.method(#getAccountsToMigrate, []), returnValue: <_i4.Account>[])
//           as List<_i4.Account>);

//   @override
//   _i3.Future<void> clearAccountsToMigrate() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearAccountsToMigrate, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> addAccount(_i4.Account? account) =>
//       (super.noSuchMethod(
//             Invocation.method(#addAccount, [account]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> updateAccount(_i4.Account? account) =>
//       (super.noSuchMethod(
//             Invocation.method(#updateAccount, [account]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> removeAccount(_i4.Account? account) =>
//       (super.noSuchMethod(
//             Invocation.method(#removeAccount, [account]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> setActiveAccount(_i4.Account? account) =>
//       (super.noSuchMethod(
//             Invocation.method(#setActiveAccount, [account]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<_i4.Account?> getActiveAccount() =>
//       (super.noSuchMethod(Invocation.method(#getActiveAccount, []), returnValue: _i3.Future<_i4.Account?>.value())
//           as _i3.Future<_i4.Account?>);

//   @override
//   _i3.Future<_i4.Account?> getAccount({required int index, required int walletIndex}) =>
//       (super.noSuchMethod(Invocation.method(#getAccount, [index]), returnValue: _i3.Future<_i4.Account?>.value())
//           as _i3.Future<_i4.Account?>);

//   @override
//   _i3.Future<int> getNextFreeAccountIndex(int walletIndex) =>
//       (super.noSuchMethod(Invocation.method(#getNextFreeAccountIndex, []), returnValue: _i3.Future<int>.value(0))
//           as _i3.Future<int>);

//   @override
//   _i3.Future<bool> getHasWallet() =>
//       (super.noSuchMethod(Invocation.method(#getHasWallet, []), returnValue: _i3.Future<bool>.value(false))
//           as _i3.Future<bool>);

//   @override
//   _i3.Future<bool> isWalletLoggedOut() =>
//       (super.noSuchMethod(Invocation.method(#isWalletLoggedOut, []), returnValue: _i3.Future<bool>.value(false))
//           as _i3.Future<bool>);

//   @override
//   _i3.Future<void> setMnemonic(String? mnemonic, int? mnemonicIndex) =>
//       (super.noSuchMethod(
//             Invocation.method(#setMnemonic, [mnemonic]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<String?> getMnemonic(int? mnemonicIndex) =>
//       (super.noSuchMethod(Invocation.method(#getMnemonic, []), returnValue: _i3.Future<String?>.value())
//           as _i3.Future<String?>);

//   @override
//   _i3.Future<void> setReversibleTimeSeconds(int? seconds) =>
//       (super.noSuchMethod(
//             Invocation.method(#setReversibleTimeSeconds, [seconds]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<int?> getReversibleTimeSeconds() =>
//       (super.noSuchMethod(Invocation.method(#getReversibleTimeSeconds, []), returnValue: _i3.Future<int?>.value())
//           as _i3.Future<int?>);

//   @override
//   _i3.Future<bool?> getBool(String? key) =>
//       (super.noSuchMethod(Invocation.method(#getBool, [key]), returnValue: _i3.Future<bool?>.value())
//           as _i3.Future<bool?>);

//   @override
//   _i3.Future<void> setBool(String? key, bool? value) =>
//       (super.noSuchMethod(
//             Invocation.method(#setBool, [key, value]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<String?> getString(String? key) =>
//       (super.noSuchMethod(Invocation.method(#getString, [key]), returnValue: _i3.Future<String?>.value())
//           as _i3.Future<String?>);

//   @override
//   void setLastSuccessfulAuthTime(DateTime? time) =>
//       super.noSuchMethod(Invocation.method(#setLastSuccessfulAuthTime, [time]), returnValueForMissingStub: null);

//   @override
//   void setAuthTimeout(int? timeoutDurationInMinutes) => super.noSuchMethod(
//     Invocation.method(#setAuthTimeout, [timeoutDurationInMinutes]),
//     returnValueForMissingStub: null,
//   );

//   @override
//   void setAuthEnabled(bool? enabled) =>
//       super.noSuchMethod(Invocation.method(#setAuthEnabled, [enabled]), returnValueForMissingStub: null);

//   @override
//   bool isAuthEnabled() => (super.noSuchMethod(Invocation.method(#isAuthEnabled, []), returnValue: false) as bool);

//   @override
//   bool hasOldAccounts() => (super.noSuchMethod(Invocation.method(#hasOldAccounts, []), returnValue: false) as bool);

//   @override
//   List<_i4.Account> getOldAccounts() =>
//       (super.noSuchMethod(Invocation.method(#getOldAccounts, []), returnValue: <_i4.Account>[]) as List<_i4.Account>);

//   @override
//   _i3.Future<void> clearOldAccounts() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearOldAccounts, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<void> setOldAccountsData(String? jsonData) =>
//       (super.noSuchMethod(
//             Invocation.method(#setOldAccountsData, [jsonData]),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   void resetForTest() => super.noSuchMethod(Invocation.method(#resetForTest, []), returnValueForMissingStub: null);

//   @override
//   _i3.Future<void> clearAll() =>
//       (super.noSuchMethod(
//             Invocation.method(#clearAll, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   bool referralCheckCompleted() =>
//       (super.noSuchMethod(Invocation.method(#referralCheckCompleted, []), returnValue: false) as bool);

//   @override
//   void setReferralCheckCompleted() =>
//       super.noSuchMethod(Invocation.method(#setReferralCheckCompleted, []), returnValueForMissingStub: null);

//   @override
//   void clearReferralCheckCompletedFlag() =>
//       super.noSuchMethod(Invocation.method(#clearReferralCheckCompletedFlag, []), returnValueForMissingStub: null);

//   @override
//   void setReferralCode(String? code) =>
//       super.noSuchMethod(Invocation.method(#setReferralCode, [code]), returnValueForMissingStub: null);

//   @override
//   bool hasWatchedQuestsPromo() =>
//       (super.noSuchMethod(Invocation.method(#hasWatchedQuestsPromo, []), returnValue: false) as bool);

//   @override
//   void setQuestsPromoWatched() =>
//       super.noSuchMethod(Invocation.method(#setQuestsPromoWatched, []), returnValueForMissingStub: null);

//   @override
//   void clearQuestsPromoWatchedFlag() =>
//       super.noSuchMethod(Invocation.method(#clearQuestsPromoWatchedFlag, []), returnValueForMissingStub: null);

//   @override
//   bool existingUserSeenPromoVideo() =>
//       (super.noSuchMethod(Invocation.method(#existingUserSeenPromoVideo, []), returnValue: false) as bool);

//   @override
//   void setExistingUserSeenPromoVideo() =>
//       super.noSuchMethod(Invocation.method(#setExistingUserSeenPromoVideo, []), returnValueForMissingStub: null);

//   @override
//   void clearExistingUserSeenPromoVideoFlag() =>
//       super.noSuchMethod(Invocation.method(#clearExistingUserSeenPromoVideoFlag, []), returnValueForMissingStub: null);
// }

// /// A class which mocks [SubstrateService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockSubstrateService extends _i1.Mock implements _i2.SubstrateService {
//   MockSubstrateService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<BigInt> getFee(_i5.Uint8List? signedExtrinsic) =>
//       (super.noSuchMethod(
//             Invocation.method(#getFee, [signedExtrinsic]),
//             returnValue: _i3.Future<BigInt>.value(
//               _i6.dummyValue<BigInt>(this, Invocation.method(#getFee, [signedExtrinsic])),
//             ),
//           )
//           as _i3.Future<BigInt>);

//   @override
//   _i3.Future<BigInt> queryUserBalance() =>
//       (super.noSuchMethod(
//             Invocation.method(#queryUserBalance, []),
//             returnValue: _i3.Future<BigInt>.value(
//               _i6.dummyValue<BigInt>(this, Invocation.method(#queryUserBalance, [])),
//             ),
//           )
//           as _i3.Future<BigInt>);

//   @override
//   _i3.Future<BigInt> queryBalance(String? address) =>
//       (super.noSuchMethod(
//             Invocation.method(#queryBalance, [address]),
//             returnValue: _i3.Future<BigInt>.value(
//               _i6.dummyValue<BigInt>(this, Invocation.method(#queryBalance, [address])),
//             ),
//           )
//           as _i3.Future<BigInt>);

//   @override
//   _i2.Keypair nonHDdilithiumKeypairFromMnemonic(String? senderSeed) =>
//       (super.noSuchMethod(
//             Invocation.method(#nonHDdilithiumKeypairFromMnemonic, [senderSeed]),
//             returnValue: _FakeKeypair_0(this, Invocation.method(#nonHDdilithiumKeypairFromMnemonic, [senderSeed])),
//           )
//           as _i2.Keypair);

//   @override
//   _i3.Future<_i2.ExtrinsicFeeData> getFeeForCall(_i4.Account? account, _i2.RuntimeCall? call) =>
//       (super.noSuchMethod(
//             Invocation.method(#getFeeForCall, [account, call]),
//             returnValue: _i3.Future<_i2.ExtrinsicFeeData>.value(
//               _FakeExtrinsicFeeData_1(this, Invocation.method(#getFeeForCall, [account, call])),
//             ),
//           )
//           as _i3.Future<_i2.ExtrinsicFeeData>);

//   @override
//   _i3.Future<_i5.Uint8List> submitExtrinsic(_i4.Account? account, _i2.RuntimeCall? call, {int? maxRetries = 3}) =>
//       (super.noSuchMethod(
//             Invocation.method(#submitExtrinsic, [account, call], {#maxRetries: maxRetries}),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i2.ExtrinsicData> getExtrinsicPayload(_i4.Account? account, _i2.RuntimeCall? call) =>
//       (super.noSuchMethod(
//             Invocation.method(#getExtrinsicPayload, [account, call]),
//             returnValue: _i3.Future<_i2.ExtrinsicData>.value(
//               _FakeExtrinsicData_2(this, Invocation.method(#getExtrinsicPayload, [account, call])),
//             ),
//           )
//           as _i3.Future<_i2.ExtrinsicData>);

//   @override
//   _i3.Future<void> logout() =>
//       (super.noSuchMethod(
//             Invocation.method(#logout, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<String> generateMnemonic() =>
//       (super.noSuchMethod(
//             Invocation.method(#generateMnemonic, []),
//             returnValue: _i3.Future<String>.value(
//               _i6.dummyValue<String>(this, Invocation.method(#generateMnemonic, [])),
//             ),
//           )
//           as _i3.Future<String>);

//   @override
//   bool isValidSS58Address(String? address) =>
//       (super.noSuchMethod(Invocation.method(#isValidSS58Address, [address]), returnValue: false) as bool);

//   @override
//   String bytesToHex(_i5.Uint8List? bytes) =>
//       (super.noSuchMethod(
//             Invocation.method(#bytesToHex, [bytes]),
//             returnValue: _i6.dummyValue<String>(this, Invocation.method(#bytesToHex, [bytes])),
//           )
//           as String);

//   @override
//   void dispose() => super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);
// }

// /// A class which mocks [HumanReadableChecksumService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockHumanReadableChecksumService extends _i1.Mock implements _i2.HumanReadableChecksumService {
//   MockHumanReadableChecksumService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<void> initialize() =>
//       (super.noSuchMethod(
//             Invocation.method(#initialize, []),
//             returnValue: _i3.Future<void>.value(),
//             returnValueForMissingStub: _i3.Future<void>.value(),
//           )
//           as _i3.Future<void>);

//   @override
//   _i3.Future<String> getHumanReadableName(String? address, {dynamic upperCase = true}) =>
//       (super.noSuchMethod(
//             Invocation.method(#getHumanReadableName, [address], {#upperCase: upperCase}),
//             returnValue: _i3.Future<String>.value(
//               _i6.dummyValue<String>(
//                 this,
//                 Invocation.method(#getHumanReadableName, [address], {#upperCase: upperCase}),
//               ),
//             ),
//           )
//           as _i3.Future<String>);

//   @override
//   void dispose() => super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);
// }

// /// A class which mocks [BalancesService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockBalancesService extends _i1.Mock implements _i2.BalancesService {
//   MockBalancesService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<_i5.Uint8List> balanceTransfer(_i4.Account? account, String? targetAddress, BigInt? amount) =>
//       (super.noSuchMethod(
//             Invocation.method(#balanceTransfer, [account, targetAddress, amount]),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i2.ExtrinsicFeeData> getBalanceTransferFee(_i4.Account? account, String? targetAddress, BigInt? amount) =>
//       (super.noSuchMethod(
//             Invocation.method(#getBalanceTransferFee, [account, targetAddress, amount]),
//             returnValue: _i3.Future<_i2.ExtrinsicFeeData>.value(
//               _FakeExtrinsicFeeData_1(
//                 this,
//                 Invocation.method(#getBalanceTransferFee, [account, targetAddress, amount]),
//               ),
//             ),
//           )
//           as _i3.Future<_i2.ExtrinsicFeeData>);

//   @override
//   _i2.Balances getBalanceTransferCall(String? targetAddress, BigInt? amount) =>
//       (super.noSuchMethod(
//             Invocation.method(#getBalanceTransferCall, [targetAddress, amount]),
//             returnValue: _FakeBalances_3(this, Invocation.method(#getBalanceTransferCall, [targetAddress, amount])),
//           )
//           as _i2.Balances);
// }

// /// A class which mocks [ReversibleTransfersService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockReversibleTransfersService extends _i1.Mock implements _i2.ReversibleTransfersService {
//   MockReversibleTransfersService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i3.Future<_i5.Uint8List> setHighSecurity({
//     required _i4.Account? account,
//     required _i4.Account? guardian,
//     required _i7.BlockNumberOrTimestamp? delay,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#setHighSecurity, [], {#account: account, #guardian: guardian, #delay: delay}),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i5.Uint8List> scheduleReversibleTransfer({
//     required _i4.Account? account,
//     required String? recipientAddress,
//     required BigInt? amount,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#scheduleReversibleTransfer, [], {
//               #account: account,
//               #recipientAddress: recipientAddress,
//               #amount: amount,
//             }),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i5.Uint8List> scheduleReversibleTransferWithDelay({
//     required _i4.Account? account,
//     required String? recipientAddress,
//     required BigInt? amount,
//     required _i7.BlockNumberOrTimestamp? delay,
//     void Function(_i8.ExtrinsicStatus)? onStatus,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#scheduleReversibleTransferWithDelay, [], {
//               #account: account,
//               #recipientAddress: recipientAddress,
//               #amount: amount,
//               #delay: delay,
//               #onStatus: onStatus,
//             }),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i2.ExtrinsicFeeData> getReversibleTransferWithDelayFeeEstimate({
//     required _i4.Account? account,
//     required String? recipientAddress,
//     required BigInt? amount,
//     required int? delaySeconds,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#getReversibleTransferWithDelayFeeEstimate, [], {
//               #account: account,
//               #recipientAddress: recipientAddress,
//               #amount: amount,
//               #delaySeconds: delaySeconds,
//             }),
//             returnValue: _i3.Future<_i2.ExtrinsicFeeData>.value(
//               _FakeExtrinsicFeeData_1(
//                 this,
//                 Invocation.method(#getReversibleTransferWithDelayFeeEstimate, [], {
//                   #account: account,
//                   #recipientAddress: recipientAddress,
//                   #amount: amount,
//                   #delaySeconds: delaySeconds,
//                 }),
//               ),
//             ),
//           )
//           as _i3.Future<_i2.ExtrinsicFeeData>);

//   @override
//   _i2.ReversibleTransfers getReversibleTransferCall(
//     String? recipientAddress,
//     BigInt? amount,
//     _i7.BlockNumberOrTimestamp? delay,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#getReversibleTransferCall, [recipientAddress, amount, delay]),
//             returnValue: _FakeReversibleTransfers_4(
//               this,
//               Invocation.method(#getReversibleTransferCall, [recipientAddress, amount, delay]),
//             ),
//           )
//           as _i2.ReversibleTransfers);

//   @override
//   _i3.Future<_i5.Uint8List> scheduleReversibleTransferWithDelaySeconds({
//     required _i4.Account? account,
//     required String? recipientAddress,
//     required BigInt? amount,
//     required int? delaySeconds,
//     void Function(_i8.ExtrinsicStatus)? onStatus,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#scheduleReversibleTransferWithDelaySeconds, [], {
//               #account: account,
//               #recipientAddress: recipientAddress,
//               #amount: amount,
//               #delaySeconds: delaySeconds,
//               #onStatus: onStatus,
//             }),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i5.Uint8List> cancelReversibleTransfer({
//     required _i4.Account? account,
//     required List<int>? transactionId,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#cancelReversibleTransfer, [], {#account: account, #transactionId: transactionId}),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i5.Uint8List> executeTransfer({required _i4.Account? account, required List<int>? transactionId}) =>
//       (super.noSuchMethod(
//             Invocation.method(#executeTransfer, [], {#account: account, #transactionId: transactionId}),
//             returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
//           )
//           as _i3.Future<_i5.Uint8List>);

//   @override
//   _i3.Future<_i9.HighSecurityAccountData?> getAccountReversibilityConfig(String? address) =>
//       (super.noSuchMethod(
//             Invocation.method(#getAccountReversibilityConfig, [address]),
//             returnValue: _i3.Future<_i9.HighSecurityAccountData?>.value(),
//           )
//           as _i3.Future<_i9.HighSecurityAccountData?>);

//   @override
//   _i3.Future<_i10.PendingTransfer?> getPendingTransfer(List<int>? transactionId) =>
//       (super.noSuchMethod(
//             Invocation.method(#getPendingTransfer, [transactionId]),
//             returnValue: _i3.Future<_i10.PendingTransfer?>.value(),
//           )
//           as _i3.Future<_i10.PendingTransfer?>);

//   @override
//   _i3.Future<int> getAccountPendingIndex(String? address) =>
//       (super.noSuchMethod(Invocation.method(#getAccountPendingIndex, [address]), returnValue: _i3.Future<int>.value(0))
//           as _i3.Future<int>);

//   @override
//   _i3.Future<bool> isReversibilityEnabled(String? address) =>
//       (super.noSuchMethod(
//             Invocation.method(#isReversibilityEnabled, [address]),
//             returnValue: _i3.Future<bool>.value(false),
//           )
//           as _i3.Future<bool>);

//   @override
//   _i3.Future<List<_i10.PendingTransfer>> getAccountPendingTransfers(String? address) =>
//       (super.noSuchMethod(
//             Invocation.method(#getAccountPendingTransfers, [address]),
//             returnValue: _i3.Future<List<_i10.PendingTransfer>>.value(<_i10.PendingTransfer>[]),
//           )
//           as _i3.Future<List<_i10.PendingTransfer>>);

//   @override
//   _i3.Future<Map<String, dynamic>> getConstants() =>
//       (super.noSuchMethod(
//             Invocation.method(#getConstants, []),
//             returnValue: _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
//           )
//           as _i3.Future<Map<String, dynamic>>);
// }

// /// A class which mocks [NumberFormattingService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockNumberFormattingService extends _i1.Mock implements _i2.NumberFormattingService {
//   MockNumberFormattingService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   String formatBalance(
//     BigInt? balance, {
//     int? maxDecimals = 4,
//     bool? addThousandsSeparators = true,
//     bool? addSymbol = false,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(
//               #formatBalance,
//               [balance],
//               {#maxDecimals: maxDecimals, #addThousandsSeparators: addThousandsSeparators, #addSymbol: addSymbol},
//             ),
//             returnValue: _i6.dummyValue<String>(
//               this,
//               Invocation.method(
//                 #formatBalance,
//                 [balance],
//                 {#maxDecimals: maxDecimals, #addThousandsSeparators: addThousandsSeparators, #addSymbol: addSymbol},
//               ),
//             ),
//           )
//           as String);

//   @override
//   BigInt? parseAmount(String? formattedAmount) =>
//       (super.noSuchMethod(Invocation.method(#parseAmount, [formattedAmount])) as BigInt?);
// }
