// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_account_id`

String toAccountId({required Keypair obj}) =>
    RustLib.instance.api.crateApiCryptoToAccountId(obj: obj);

Keypair generateKeypair({required String mnemonic}) =>
    RustLib.instance.api.crateApiCryptoGenerateKeypair(mnemonic: mnemonic);

class Keypair {
  final Uint8List publicKey;
  final Uint8List secretKey;

  const Keypair({
    required this.publicKey,
    required this.secretKey,
  });

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Keypair &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}
