// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:resonance_network_wallet/utils/env_utils.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions getOptionsForEnvironment() {
    if (kIsWeb) throw UnsupportedError('Web not configured');

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: EnvUtils.androidFirebaseApiKey,
          appId: '1:700047185713:android:151f32080a837021d98210',
          messagingSenderId: '700047185713',
          projectId: 'quantus-wallet',
          storageBucket: 'quantus-wallet.firebasestorage.app',
        );
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: EnvUtils.iosFirebaseApiKey,
          appId: '1:700047185713:ios:4689e532e8a4f174d98210',
          messagingSenderId: '700047185713',
          projectId: 'quantus-wallet',
          storageBucket: 'quantus-wallet.firebasestorage.app',
          iosBundleId: 'com.quantus.mobile-wallet',
        );
      default:
        throw UnsupportedError('Platform not supported');
    }
  }
}
