// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/ur.dart';
import 'api/wormhole.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HdLatticeErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WormholeProofAggregatorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregatorPtr;

  @protected
  HdLatticeError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    dynamic raw,
  );

  @protected
  WormholeProofAggregator
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    dynamic raw,
  );

  @protected
  WormholeProofAggregator
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    dynamic raw,
  );

  @protected
  HdLatticeError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    dynamic raw,
  );

  @protected
  WormholeProofAggregator
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggregatedProof dco_decode_aggregated_proof(dynamic raw);

  @protected
  BlockHeaderData dco_decode_block_header_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BlockHeaderData dco_decode_box_autoadd_block_header_data(dynamic raw);

  @protected
  Keypair dco_decode_box_autoadd_keypair(dynamic raw);

  @protected
  ProofOutputAssignment dco_decode_box_autoadd_proof_output_assignment(
    dynamic raw,
  );

  @protected
  WormholeError dco_decode_box_autoadd_wormhole_error(dynamic raw);

  @protected
  WormholeProofGenerator dco_decode_box_autoadd_wormhole_proof_generator(
    dynamic raw,
  );

  @protected
  WormholeUtxo dco_decode_box_autoadd_wormhole_utxo(dynamic raw);

  @protected
  ZkMerkleProofData dco_decode_box_autoadd_zk_merkle_proof_data(dynamic raw);

  @protected
  CircuitConfig dco_decode_circuit_config(dynamic raw);

  @protected
  CircuitGenerationResult dco_decode_circuit_generation_result(dynamic raw);

  @protected
  GeneratedProof dco_decode_generated_proof(dynamic raw);

  @protected
  Keypair dco_decode_keypair(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw);

  @protected
  ProofOutputAssignment dco_decode_proof_output_assignment(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WormholeError dco_decode_wormhole_error(dynamic raw);

  @protected
  WormholePairResult dco_decode_wormhole_pair_result(dynamic raw);

  @protected
  WormholeProofGenerator dco_decode_wormhole_proof_generator(dynamic raw);

  @protected
  WormholeResult dco_decode_wormhole_result(dynamic raw);

  @protected
  WormholeUtxo dco_decode_wormhole_utxo(dynamic raw);

  @protected
  ZkMerkleProofData dco_decode_zk_merkle_proof_data(dynamic raw);

  @protected
  HdLatticeError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  );

  @protected
  WormholeProofAggregator
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    SseDeserializer deserializer,
  );

  @protected
  WormholeProofAggregator
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    SseDeserializer deserializer,
  );

  @protected
  HdLatticeError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  );

  @protected
  WormholeProofAggregator
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggregatedProof sse_decode_aggregated_proof(SseDeserializer deserializer);

  @protected
  BlockHeaderData sse_decode_block_header_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BlockHeaderData sse_decode_box_autoadd_block_header_data(
    SseDeserializer deserializer,
  );

  @protected
  Keypair sse_decode_box_autoadd_keypair(SseDeserializer deserializer);

  @protected
  ProofOutputAssignment sse_decode_box_autoadd_proof_output_assignment(
    SseDeserializer deserializer,
  );

  @protected
  WormholeError sse_decode_box_autoadd_wormhole_error(
    SseDeserializer deserializer,
  );

  @protected
  WormholeProofGenerator sse_decode_box_autoadd_wormhole_proof_generator(
    SseDeserializer deserializer,
  );

  @protected
  WormholeUtxo sse_decode_box_autoadd_wormhole_utxo(
    SseDeserializer deserializer,
  );

  @protected
  ZkMerkleProofData sse_decode_box_autoadd_zk_merkle_proof_data(
    SseDeserializer deserializer,
  );

  @protected
  CircuitConfig sse_decode_circuit_config(SseDeserializer deserializer);

  @protected
  CircuitGenerationResult sse_decode_circuit_generation_result(
    SseDeserializer deserializer,
  );

  @protected
  GeneratedProof sse_decode_generated_proof(SseDeserializer deserializer);

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer);

  @protected
  ProofOutputAssignment sse_decode_proof_output_assignment(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WormholeError sse_decode_wormhole_error(SseDeserializer deserializer);

  @protected
  WormholePairResult sse_decode_wormhole_pair_result(
    SseDeserializer deserializer,
  );

  @protected
  WormholeProofGenerator sse_decode_wormhole_proof_generator(
    SseDeserializer deserializer,
  );

  @protected
  WormholeResult sse_decode_wormhole_result(SseDeserializer deserializer);

  @protected
  WormholeUtxo sse_decode_wormhole_utxo(SseDeserializer deserializer);

  @protected
  ZkMerkleProofData sse_decode_zk_merkle_proof_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    WormholeProofAggregator self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    WormholeProofAggregator self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    WormholeProofAggregator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aggregated_proof(
    AggregatedProof self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_block_header_data(
    BlockHeaderData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_block_header_data(
    BlockHeaderData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_keypair(Keypair self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_proof_output_assignment(
    ProofOutputAssignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wormhole_error(
    WormholeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wormhole_proof_generator(
    WormholeProofGenerator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wormhole_utxo(
    WormholeUtxo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_zk_merkle_proof_data(
    ZkMerkleProofData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_circuit_config(CircuitConfig self, SseSerializer serializer);

  @protected
  void sse_encode_circuit_generation_result(
    CircuitGenerationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generated_proof(
    GeneratedProof self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer);

  @protected
  void sse_encode_proof_output_assignment(
    ProofOutputAssignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wormhole_error(WormholeError self, SseSerializer serializer);

  @protected
  void sse_encode_wormhole_pair_result(
    WormholePairResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wormhole_proof_generator(
    WormholeProofGenerator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wormhole_result(
    WormholeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wormhole_utxo(WormholeUtxo self, SseSerializer serializer);

  @protected
  void sse_encode_zk_merkle_proof_data(
    ZkMerkleProofData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_quantus_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_quantus_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregatorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_quantus_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregatorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregatorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_quantus_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregator =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWormholeProofAggregatorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
