// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/ur.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCryptoInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1692591137;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_resonance_network_wallet',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Keypair crateApiCryptoCrystalAlice();

  Keypair crateApiCryptoCrystalBob();

  Keypair crateApiCryptoCrystalCharlie();

  Uint8List crateApiUrDecodeUr({required List<String> urParts});

  Uint8List crateApiCryptoDeriveHdPath({
    required List<int> seed,
    required String path,
  });

  List<String> crateApiUrEncodeUr({required List<int> data});

  Keypair crateApiCryptoGenerateDerivedKeypair({
    required String mnemonicStr,
    required String path,
  });

  Keypair crateApiCryptoGenerateKeypair({required String mnemonicStr});

  Keypair crateApiCryptoGenerateKeypairFromSeed({required List<int> seed});

  Future<void> crateApiCryptoInitApp();

  bool crateApiUrIsCompleteUr({required List<String> urParts});

  BigInt crateApiCryptoPublicKeyBytes();

  BigInt crateApiCryptoSecretKeyBytes();

  void crateApiCryptoSetDefaultSs58Prefix({required int prefix});

  Uint8List crateApiCryptoSignMessage({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
  });

  Uint8List crateApiCryptoSignMessageWithPubkey({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
  });

  BigInt crateApiCryptoSignatureBytes();

  Uint8List crateApiCryptoSs58ToAccountId({required String s});

  String crateApiCryptoToAccountId({required Keypair obj});

  bool crateApiCryptoVerifyMessage({
    required Keypair keypair,
    required List<int> message,
    required List<int> signature,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HdLatticeError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HdLatticeError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HdLatticeErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Keypair crateApiCryptoCrystalAlice() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoCrystalAliceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalAliceConstMeta =>
      const TaskConstMeta(debugName: 'crystal_alice', argNames: []);

  @override
  Keypair crateApiCryptoCrystalBob() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoCrystalBobConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalBobConstMeta =>
      const TaskConstMeta(debugName: 'crystal_bob', argNames: []);

  @override
  Keypair crateApiCryptoCrystalCharlie() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoCrystalCharlieConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalCharlieConstMeta =>
      const TaskConstMeta(debugName: 'crystal_charlie', argNames: []);

  @override
  Uint8List crateApiUrDecodeUr({required List<String> urParts}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(urParts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUrDecodeUrConstMeta,
        argValues: [urParts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrDecodeUrConstMeta =>
      const TaskConstMeta(debugName: 'decode_ur', argNames: ['urParts']);

  @override
  Uint8List crateApiCryptoDeriveHdPath({
    required List<int> seed,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seed, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoDeriveHdPathConstMeta,
        argValues: [seed, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDeriveHdPathConstMeta => const TaskConstMeta(
    debugName: 'derive_hd_path',
    argNames: ['seed', 'path'],
  );

  @override
  List<String> crateApiUrEncodeUr({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUrEncodeUrConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrEncodeUrConstMeta =>
      const TaskConstMeta(debugName: 'encode_ur', argNames: ['data']);

  @override
  Keypair crateApiCryptoGenerateDerivedKeypair({
    required String mnemonicStr,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicStr, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError,
        ),
        constMeta: kCrateApiCryptoGenerateDerivedKeypairConstMeta,
        argValues: [mnemonicStr, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateDerivedKeypairConstMeta =>
      const TaskConstMeta(
        debugName: 'generate_derived_keypair',
        argNames: ['mnemonicStr', 'path'],
      );

  @override
  Keypair crateApiCryptoGenerateKeypair({required String mnemonicStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoGenerateKeypairConstMeta,
        argValues: [mnemonicStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairConstMeta =>
      const TaskConstMeta(
        debugName: 'generate_keypair',
        argNames: ['mnemonicStr'],
      );

  @override
  Keypair crateApiCryptoGenerateKeypairFromSeed({required List<int> seed}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoGenerateKeypairFromSeedConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairFromSeedConstMeta =>
      const TaskConstMeta(
        debugName: 'generate_keypair_from_seed',
        argNames: ['seed'],
      );

  @override
  Future<void> crateApiCryptoInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoInitAppConstMeta =>
      const TaskConstMeta(debugName: 'init_app', argNames: []);

  @override
  bool crateApiUrIsCompleteUr({required List<String> urParts}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(urParts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUrIsCompleteUrConstMeta,
        argValues: [urParts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrIsCompleteUrConstMeta =>
      const TaskConstMeta(debugName: 'is_complete_ur', argNames: ['urParts']);

  @override
  BigInt crateApiCryptoPublicKeyBytes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoPublicKeyBytesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPublicKeyBytesConstMeta =>
      const TaskConstMeta(debugName: 'public_key_bytes', argNames: []);

  @override
  BigInt crateApiCryptoSecretKeyBytes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSecretKeyBytesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSecretKeyBytesConstMeta =>
      const TaskConstMeta(debugName: 'secret_key_bytes', argNames: []);

  @override
  void crateApiCryptoSetDefaultSs58Prefix({required int prefix}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(prefix, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSetDefaultSs58PrefixConstMeta,
        argValues: [prefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSetDefaultSs58PrefixConstMeta =>
      const TaskConstMeta(
        debugName: 'set_default_ss58_prefix',
        argNames: ['prefix'],
      );

  @override
  Uint8List crateApiCryptoSignMessage({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_opt_u_8_array_32(entropy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSignMessageConstMeta,
        argValues: [keypair, message, entropy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignMessageConstMeta => const TaskConstMeta(
    debugName: 'sign_message',
    argNames: ['keypair', 'message', 'entropy'],
  );

  @override
  Uint8List crateApiCryptoSignMessageWithPubkey({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_opt_u_8_array_32(entropy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSignMessageWithPubkeyConstMeta,
        argValues: [keypair, message, entropy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignMessageWithPubkeyConstMeta =>
      const TaskConstMeta(
        debugName: 'sign_message_with_pubkey',
        argNames: ['keypair', 'message', 'entropy'],
      );

  @override
  BigInt crateApiCryptoSignatureBytes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSignatureBytesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignatureBytesConstMeta =>
      const TaskConstMeta(debugName: 'signature_bytes', argNames: []);

  @override
  Uint8List crateApiCryptoSs58ToAccountId({required String s}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoSs58ToAccountIdConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSs58ToAccountIdConstMeta =>
      const TaskConstMeta(debugName: 'ss58_to_account_id', argNames: ['s']);

  @override
  String crateApiCryptoToAccountId({required Keypair obj}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(obj, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoToAccountIdConstMeta,
        argValues: [obj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoToAccountIdConstMeta =>
      const TaskConstMeta(debugName: 'to_account_id', argNames: ['obj']);

  @override
  bool crateApiCryptoVerifyMessage({
    required Keypair keypair,
    required List<int> message,
    required List<int> signature,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoVerifyMessageConstMeta,
        argValues: [keypair, message, signature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoVerifyMessageConstMeta =>
      const TaskConstMeta(
        debugName: 'verify_message',
        argNames: ['keypair', 'message', 'signature'],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HdLatticeError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HdLatticeError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError;

  @protected
  HdLatticeError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HdLatticeError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Keypair dco_decode_box_autoadd_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_keypair(raw);
  }

  @protected
  Keypair dco_decode_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Keypair(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      secretKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_u_8_array_32(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  HdLatticeError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HdLatticeError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Keypair sse_decode_box_autoadd_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_keypair(deserializer));
  }

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secretKey = sse_decode_list_prim_u_8_strict(deserializer);
    return Keypair(publicKey: var_publicKey, secretKey: var_secretKey);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_u_8_array_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HdLatticeErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HdLatticeErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_keypair(Keypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_keypair(self, serializer);
  }

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.secretKey, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_u_8_array_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class HdLatticeErrorImpl extends RustOpaque implements HdLatticeError {
  // Not to be used by end users
  HdLatticeErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HdLatticeErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HdLatticeError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HdLatticeError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HdLatticeErrorPtr,
  );
}
