name: Build Windows Test

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-windows:
    name: Build Windows Test Artifact
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./miner-app
        env:
          GIT_TERMINAL_PROMPT: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Windows release
        run: flutter build windows --release
        working-directory: ./miner-app

      - name: Package Windows App
        shell: powershell
        run: |
          cd miner-app/build/windows/x64/runner/Release/
          Compress-Archive -Path * -DestinationPath quantus_miner_windows_test.zip -Force

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: quantus_miner-windows-test
          path: miner-app/build/windows/x64/runner/Release/quantus_miner_windows_test.zip

